CREATE TABLE DOCENTE(ID NUMBER(8),NOME VARCHAR(70) NOT NULL,CPF NUMBER(11) NOT NULL,
DT_CAD DATE DEFAULT SYSDATE, DT_NASC DATE NOT NULL,  ENDERECO VARCHAR(50) NOT NULL ,  TELEFONE NUMBER(12),  FOTO BLOB,
RESIPDF BLOB,  SALA_ID NUMBER(3),  SALARIO NUMBER (8,2), EMAIL VARCHAR(30),  SENHA VARCHAR(20) NOT NULL, GERENTE_ID NUMBER(8),
CONSTRAINT PK_DOCENTE PRIMARY KEY (ID),CONSTRAINT FK_DOCENTE_GERENTE FOREIGN KEY (GERENTE_ID) REFERENCES DOCENTE(ID),
CONSTRAINT FK_DOC_SALA FOREIGN KEY (SALA_ID)REFERENCES SALA(SALA_ID));

CREATE TABLE ALUNO(ID NUMBER(8),NOME VARCHAR(70) NOT NULL,CPF NUMBER(11) NOT NULL,
DT_CAD DATE DEFAULT SYSDATE,DT_NASC DATE NOT NULL,ENDERECO VARCHAR(50) NOT NULL ,TELEFONE NUMBER(12),FOTO BLOB,
RESIPDF BLOB,ATIVO CHAR(1) DEFAULT 'S' , EMAIL VARCHAR(30),
CONSTRAINT PK_ALUNO PRIMARY KEY (ID),CONSTRAINT CHECK_ALUNO CHECK( ATIVO IN ('S','N','s','n')));

CREATE TABLE MATERIAS( MATERIA_ID VARCHAR(10),DESCR VARCHAR(30),CONSTRAINT PK_MATERIAS PRIMARY KEY(MATERIA_ID));

CREATE TABLE  SALA( ID NUMBER (3),DOCENTE_ID NUMBER(8), DESCR VARCHAR(20), CONSTRAINT PK_SALA PRIMARY KEY(ID),
CONSTRAINT FK_DOCENTE FOREIGN KEY(DOCENTE_ID) REFERENCES DOCENTE(ID)) ;

CREATE TABLE SALA_MATERIA( SALA_ID NUMBER(3),MATERIA_ID VARCHAR(10),HORARIO_ID NUMBER(3), DIA VARCHAR(10),
CONSTRAINT FK_HORARIO FOREIGN KEY(HORARIO_ID) REFERENCES HORARIO(ID),
CONSTRAINT FK_MATERIA FOREIGN KEY(MATERIA_ID) REFERENCES MATERIAS(MATERIA_ID),
CONSTRAINT FK_SALA FOREIGN KEY(SALA_ID) REFERENCES SALA(ID));

CREATE TABLE HORARIO( ID NUMBER(3), HORARIO VARCHAR(10), CONSTRAINT PK_HORARIO PRIMARY KEY(ID)); 

CREATE TABLE SALA_ALUNO( SALA_ID NUMBER(3),ALUNO_ID NUMBER(8), 
CONSTRAINT FK_ALUNOS FOREIGN KEY(ALUNO_ID) REFERENCES ALUNO(ID), CONSTRAINT FK_SSALA FOREIGN KEY(SALA_ID) REFERENCES SALA(ID));

CREATE SEQUENCE  DOCENTE_ID  MINVALUE 10000 MAXVALUE 999999999 INCREMENT BY 10 START WITH 10400 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  ALUNO_ID  MINVALUE 10000 MAXVALUE 999999999 INCREMENT BY 10 START WITH 10400 CACHE 20 NOORDER  NOCYCLE 

INSERT INTO ALUNO (ID,NOME,CPF,DT_NASC,ENDERECO,TELEFONE,EMAIL, FOTO, RESIPDF) VALUES(ALUNO_ID.NEXTVAL, ,  ,, , ,, ,);

INSERT INTO DOCENTE (ID,NOME,SENHA,CPF,DT_NASC,ENDERECO,TELEFONE,EMAIL, SALA_ID,FOTO, RESIPDF) VALUES(DOCENTE_ID.NEXTVAL,);

INSERT INTO SALA_ALUNO(SALA_ID,ALUNO_ID) VALUES (1,(SELECT ID FROM ALUNO WHERE DT_CAD IN (SELECT MAX(DT_CAD) FROM ALUNO)));

SELECT ID FROM ALUNO WHERE DT_CAD IN (SELECT MAX(DT_CAD) FROM ALUNO);
SELECT ID,NOME,SENHA FROM DOCENTE WHERE DT_CAD IN (SELECT MAX(DT_CAD) FROM DOCENTE);


INSERT INTO SALA_MATERIA(SALA_ID, MATERIA_ID,HORARIO) VALUES (1,'PT', TO_DATE('FRIDAY 15:00','DAY HH24:MI'));
SELECT * FROM SALA_MATERIA;
select TO_CHAR(SYSDATE,'DAY') FROM DUAL;
DELETE FROM SALA_MATERIA;

INSERT INTO SALA(ID,DOCENTE_ID,DESCR) VALUES (1,10400,'3ºAno Ensino médio');

INSERT INTO SALA_ALUNO(SALA_ID,ALUNO_ID) VALUES (1, (SELECT ID FROM ALUNO WHERE DT_CAD IN (SELECT MAX(DT_CAD) FROM ALUNO)));

INSERT INTO MATERIAS(MATERIA_ID, DESCR) VALUES('PT','Português');
INSERT INTO MATERIAS(MATERIA_ID, DESCR) VALUES('HIS','História');
INSERT INTO MATERIAS(MATERIA_ID, DESCR) VALUES('GEO','Geografia');
INSERT INTO MATERIAS(MATERIA_ID, DESCR) VALUES('EDF','Educação Física');
INSERT INTO MATERIAS(MATERIA_ID, DESCR) VALUES('EDA','Educação Artistica');
INSERT INTO MATERIAS(MATERIA_ID, DESCR) VALUES('ING','Inglês');
INSERT INTO MATERIAS(MATERIA_ID, DESCR) VALUES('MUS','Música');
INSERT INTO MATERIAS(MATERIA_ID, DESCR) VALUES('MAT','Matemática');
INSERT INTO MATERIAS(MATERIA_ID, DESCR) VALUES('BIO','Biologia');
INSERT INTO MATERIAS(MATERIA_ID, DESCR) VALUES('FIS','Física');
INSERT INTO MATERIAS(MATERIA_ID, DESCR) VALUES('QUI','Química');

INSERT INTO HORARIO(ID, HORARIO) VALUES(1,'07:00');
INSERT INTO HORARIO(ID, HORARIO) VALUES(2,'07:50');
INSERT INTO HORARIO(ID, HORARIO) VALUES(3,'08:40' );
INSERT INTO HORARIO(ID, HORARIO) VALUES(4,'09:30');
INSERT INTO HORARIO(ID, HORARIO) VALUES(5,'10:40');
INSERT INTO HORARIO(ID, HORARIO) VALUES(6,'11:30');
INSERT INTO HORARIO(ID, HORARIO) VALUES(7,'12:20');
INSERT INTO HORARIO(ID, HORARIO) VALUES(8,'13:00');
INSERT INTO HORARIO(ID, HORARIO) VALUES(9,'13:50');
INSERT INTO HORARIO (ID, HORARIO) VALUES(10,'14:40');
INSERT INTO HORARIO(ID, HORARIO) VALUES(11,'15:30');
INSERT INTO HORARIO(ID, HORARIO) VALUES(12,'16:40');
INSERT INTO HORARIO(ID, HORARIO) VALUES(13,'17:30');
INSERT INTO HORARIO(ID, HORARIO) VALUES(14,'18:20');
INSERT INTO SALA_MATERIA(SALA_ID, MATERIA_ID ,HORARIO_ID) VALUES(1,'FIS',2);

SELECT DISTINCT H.HORARIO ,M.DESCR
FROM ALUNO AL, HORARIO H, MATERIAS M,SALA_MATERIA SM, SALA S,SALA_ALUNO SL 
WHERE AL.ID = SL.ALUNO_ID   AND   SL.SALA_ID = S.ID   AND   S.ID = SM.SALA_ID   AND SM.MATERIA_ID = M.MATERIA_ID AND SM.HORARIO_ID = H.ID ORDER BY 1  ;

SELECT S.DESCR,D.ID,D.NOME FROM SALA S ,DOCENTE D WHERE D.ID =10400 AND S.DOCENTE_ID = 10400;

SELECT * FROM SALA_MATERIA;
SELECT S.SALA_ID,S.MATERIA_ID,M.DESCR FROM SALA_MATERIA S, MATERIAS M WHERE S.MATERIA_ID = M.MATERIA_ID;



////
CREATE TABLE Q (CODIGO NUMBER (1) PRIMARY KEY, HORARIO DATE);
INSERT INTO Q(CODIGO,HORARIO) VALUES (2,TO_DATE('08/05/2018 20:00','DD/MM/YYYY HH24:MI'));
SELECT * FROM Q;
SELECT LOWER(TO_CHAR(HORARIO, 'DAY HH24:MI'))AS "HORARIO" FROM Q WHERE TO_CHAR(HORARIO, 'DAY') = TO_CHAR(SYSDATE,'DAY');
ALTER TABLE Q MODIFY CODIGO NUMBER(6);
DELETE FROM Q;
SELECT TO_CHAR(HORARIO,'HH24:MI') FROM Q;
 
 BEGIN
  FOR i IN 1..220 LOOP
    IF( TO_CHAR(SYSDATE-1+1,'DAY') NOT IN ('SABADO', 'DOMINGO') )
    THEN
      INSERT INTO Q(CODIGO, HORARIO)
        VALUES (I, (to_date(sysdate,'DD-MM-YYYY HH24:MI ')-1)+i);
    END IF;
  END LOOP;
 END;//
 SELECT TO_CHAR(SYSDATE, 'DAY HH24:MI') FROM DUAL WHERE TO_CHAR(SYSDATE,'HH24:MI')= '14:58';
 
SELECT SM.DIA,H.HORARIO,M.DESCR FROM SALA_MATERIA SM,HORARIO H,MATERIAS M  WHERE SM.HORARIO_ID = H.ID 
AND SM.MATERIA_ID = M.MATERIA_ID AND TO_CHAR(SYSDATE,'DAY') = SM.DIA ORDER BY H.HORARIO;
//
INSERT INTO SALA_MATERIA(SALA_ID,MATERIA_ID,HORARIO_ID,DIA) VALUES (1,'HIS',6,'QUINTA-FEIRA '); 